#!/bin/bash

# whoami, whereami
# b=basename m=me a=absolute p=path ca=canonical
declare bm apm me ca_me ca_dir
bm="$(basename "$0")";apm="$(cd "$(dirname "$0")"&&pwd)/$bm"
[ "$(which "$bm")" = "$apm" ]&&me="$bm"||me="$apm"
ca_me="$(readlink -e "$apm")";ca_dir="$(dirname "$ca_me")"

cd "$ca_dir/.."

# Ensure we have the correct number of arguments
if [[ "$#" -lt 2 ]]; then
    echo "Usage: $0 <input_script> <output_script> [test]"
    exit 1
fi

# Source the configure file
source config/configure
# Source the secrets configure file if exists
[ -f config/secrets ] && source config/secrets
# Source the placeholders file
source config/placeholders

# Declare variables
declare input_script output_script test_mode scriptname tempfile placeholder placeholder_pattern
# Assign the arguments to variables
input_script="$1" output_script="$2" test_mode="$3"

if [ "$test_mode" = 'test' ]; then
    scriptname="$(basename $input_script)-test"
else
    scriptname=$(basename $input_script)
fi

# copy the input script to the output script
cp "$input_script" $output_script

tempfile=$(mktemp)

# Replace placeholders with their actual contents
for placeholder in "${placeholders[@]}"; do
    placeholder_pattern="__${placeholder}__"
    awk '/'$placeholder_pattern'/ { system("tools/placeholders-replace '$placeholder' '$scriptname'"); next } 1' $output_script > $tempfile
    cat $tempfile > $output_script
done
rm -f $tempfile

# disable integrity check for local server
$LOCAL_SERVER&&echo -e "v=true\nnohash" >> "$output_script"

exit 0

