#!/bin/bash

declare -A bool
bool[debug]=false
bool[verbose]=false

# whoami, whereami
# b=basename m=me a=absolute p=path ca=canonical
declare bm apm me ca_me ca_dir
bm="$(basename "$0")"; apm="$(cd "$(dirname "$0")"&&pwd)/$bm"
[ "$(command -v "$bm")" = "$apm" ] && me="$bm" || me="$apm"
ca_me="$(readlink -e "$apm")"; ca_dir="$(dirname "$ca_me")"

cd "$ca_dir/.."

# source common functions
source tools/common_build_functions

${bool[debug]} && set -x

declare channel dir1 dir2 lib libname libname_in_1 libname_in_2
declare -a difflibs=()
channel="$1" # target channel
dir1="$MBUILD_DIR" # $ca_dir/../build/modules
dir2="$DATA_DIR/$target_modules_dir/${channel:=prod}" # /nc/dat/data/ich/files/Documents/Coding/ebtb/modules/${channel:=prod}

${bool[verbose]} && echo "  dir1: $dir1"
${bool[verbose]} && echo "  dir2: $dir2"
${bool[verbose]} && anykey
${bool[verbose]} && echo "  checking libs:"

#trap 'set +x;read -rp "$(printf "\033[0;31m")[DEBUG:]$(printf "\033[0;m") press Enter to proceed...";set -x' DEBUG
for lib in $(${X[find]} $dir1 -type f -exec sh -c 'head -n 1 "$1" | grep -qs BASHLIB' _ {} \; -print); do
    libname="${lib#$dir1/}"
    # Use -E to enable extended regex (so we can use “?” quantifier without backslashes).
    # (${MODULES_DIR}/)? : optionally to match minified libs as well
    libname_in_1="$(${X[head]} -n2 "$lib" | ${X[tail]} -n1 | ${X[sed]} -E "s|^# ($MODULES_DIR/)?@channel@/||")"
    libname_in_2="$(${X[head]} -n2 "$dir2/$libname" | ${X[tail]} -n1 | ${X[sed]} -E "s|^# ($MODULES_DIR/)?$channel/||")"
    ${bool[verbose]} && echo "  - \"$libname\""
    ${bool[verbose]} && echo "    1: \"$libname_in_1\"  2: \"$libname_in_2\""
    # Only modules that difference in body or path/name
#    if [[ $libname_in_1 != $libname_in_2 ]] || ! q0 ${X[diff]} <(q2 ${X[tail]} -n +4 "$lib") <(q2 ${X[tail]} -n +4 "$dir2/$libname"); then
    if [[ $libname_in_1 != $libname_in_2 ]] || ! q0 ${X[diff]} <(q2 ${X[sed]} '1,3d; /_LIB_VERSION/d' "$lib") <(q2 ${X[sed]} '1,3d; /_LIB_VERSION/d' "$dir2/$libname"); then
        ${bool[verbose]} && echo "                  - different"
        difflibs+=("$libname")
        ${bool[verbose]} && echo "${#difflibs[@]}"
    else
        ${bool[verbose]} && echo "        - equal"
    fi
    ${bool[verbose]} && anykey
done
${bool[verbose]} && echo
${bool[verbose]} && echo "  number of different libs = ${#difflibs[@]}"
${bool[verbose]} && anykey
if (( ${#difflibs[@]} )); then
    ${bool[verbose]} && echo "  found ${#difflibs[@]} different libs:"
    for i in ${!difflibs[@]}; do
        ${bool[verbose]} && echo "  - ${difflibs[i]}" || echo "${difflibs[i]}"
    done
else
    ${bool[verbose]} && echo "  all libs are equal, nothing changed"
fi
${bool[verbose]} && anykey
${bool[debug]} && set +x

