#!/bin/bash

# whoami, whereami
# b=basename m=me a=absolute p=path ca=canonical
declare bm apm me ca_me ca_dir
bm="$(basename "$0")"; apm="$(cd "$(dirname "$0")" && pwd)/$bm"
[ "$(command -v "$bm")" = "$apm" ] && me="$bm" || me="$apm"
ca_me="$(readlink -e "$apm")"; ca_dir="$(dirname "$ca_me")"

cd "$ca_dir/.."

# source common functions
source tools/common_build_functions

sign_(){
    local script scriptname target hash
    local -i size epoch

    script="$1"
    scriptname="$(${X[basename]} "$script")"

    target="$DATA_DIR/$target_scripts_dir/$scriptname"

    # first strip old signatures before signing
    echo "    strip old signature"
    ${X[sed]} -i -n '/^-----BEGIN PGP SIGNATURE-----$/q;p' "$script"
    ${X[sed]} -i -n '/^\(v\|verified\)=\(true\|false\)$/q;p' "$script"

    # sign script
    ${X[gpg]} --yes --default-key $OpenPGP_Key --armor --detach-sign "$script"

    # add "verified" flag for integrity test
    echo "    add 'v=false' flag for integrity test"
    echo "v=false" >> "$script.asc"

    # calculate hash
    echo "    calculate and add sha256sum"
    hash=$(${X[sha256sum]} "$script" | ${X[gawk]} '{printf $1}')
    echo "# sha256sum: $hash" >> "$script.asc"

    # append signature and hash
    echo "    append new signature"
    ${X[cat]} "$script.asc" >> "$script" && rm "$script.asc"

    # calculate size and (new) hash before copying to target
    epoch=$(epoch_ "$script")
    size=$(${X[stat]} -c%s  "$script")
    hash=$(${X[sha256sum]} "$script" | awk '{printf $1}')

    # copy file to target
    echo "    copy '$script' to '$target'"
    ${X[cp]} "$script" "$target"

    # create json object
    echo "    create json object '$target.json'"
    ${X[jq]} -n --compact-output --arg scriptname "$scriptname" --arg epoch "$epoch" --arg size "$size" --arg hash "$hash" \
      '{ name: $scriptname, epoch: $epoch, size: $size, hash: $hash }' > "$target.json"
}

scan_(){
    ${X[chown]} -R $HT_USER:$HT_USER "$DATA_DIR/$target_scripts_dir"
    occ files:scan --path="$target_scripts_dir"
}

(( $# )) && {
    echo "  signing this scripts"
    echo "  - $@"
    anykey
} || {
    echo "  no scripts past to sign"
    exit 1
}

for script2sign in "$@"; do
    sign_ "$script2sign"
done

echo "  scan files"
scan_

exit 0

